############# 简体中文导航 ##############

# 主菜单
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "博客"
url = "/blog"
weight = 2

[[main]]
name = "分类"
url = "/categories"
weight = 3

[[main]]
name = "关于"
url = "/about"
weight = 4

[[main]]
name = "联系"
url = "/contact"
weight = 5









# 页脚菜单
[[footer]]
name = "关于"
url = "/about"
weight = 1

[[footer]]
name = "元素"
url = "/elements"
weight = 2

[[footer]]
name = "隐私政策"
url = "/privacy-policy"
weight = 3