name: Update File to Issue

on:
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Issue Number to attach image to'
        required: true
        type: number
      fileUrl:
        description: 'File URL to upload'
        required: true
        type: string

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download File
        run: |
          mkdir -p ./.github/workflows/assets
          curl -L ${{ github.event.inputs.fileUrl }} -o ./.github/workflows/assets/image.jpg
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Upload File to Repository
        uses: LasyIsLazy/github-upload-action@v0.2.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          file-path: ./.github/workflows/assets/image.jpg
          owner: yougikou
          repo: ${{ github.repository }}
          remote-dir: /assets/${{ github.run_id }}-image.jpg
      - name: Add Image to Issue
        uses: julien-deramond/update-issue-body@v1.1.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            **Edit**: '![img](https://github.com/${{ github.repository }}/blob/main/assets/${{ github.run_id }}-image.jpg?raw=true)'
          edit-mode: append
          append-separator: space
