name: Update File to Issue

on:
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Issue Number to attach image to'
        required: true
        type: string
      fileUrl:
        description: 'File URL to upload'
        required: true
        type: string

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload File to Repository
        uses: wow-actions/download-upload@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          url: ${{ github.event.inputs.fileUrl }}
          dir: /assets
          filename: ${{ github.event.inputs.issueNumber }}-image.jpg
      - name: Add Image to Issue
        uses: julien-deramond/update-issue-body@v1.1.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            **Edit**: '![img](https://github.com/yougikou/yougikou.github.io/blob/master/assets/${{ github.event.inputs.issueNumber }}-image.jpg?raw=true)'
          edit-mode: append
          append-separator: space
