name: Download and Update GeoJSON

on:
  issues:
    types: [opened]

jobs:
  download-and-update-geojson:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check if issue has 'route' label
        id: check-label
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const issueLabels = context.payload.issue.labels;
            const hasRouteLabel = issueLabels.some(label => label.name === 'route');
            console.log(`Issue has 'route' label: ${hasRouteLabel}`);
            return hasRouteLabel;
          result-encoding: string
        env:
          HAS_ROUTE_LABEL: ${{ steps.check-label.outputs.result }}

      - name: Extract GeoJSON URL
        if: env.HAS_ROUTE_LABEL == 'true'
        id: extract-url
        run: |
          GEOJSON_URL=$(echo "${{ github.event.issue.body }}" | grep "geojson:" | sed -n "s/^.*geojson: '\[file\](\(.*\))'.*$/\1/p")
          echo "GEOJSON_URL=${GEOJSON_URL}" >> $GITHUB_ENV
        shell: bash
        
      - name: Download File
        if: env.HAS_ROUTE_LABEL == 'true'
        id: download-file
        run: |
          curl -X GET '${{ env.GEOJSON_URL }}' -H 'accept: */*' -o ./${{ github.event.issue.number }}-route.geojson

      - name: Upload to GitHub
        if: env.HAS_ROUTE_LABEL == 'true'
        id: upload-file
        uses: LasyIsLazy/github-upload-action@v0.2.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          file-path: ./${{ github.event.issue.number }}-route.geojson
          owner: yougikou
          repo: yougikou.github.io
          remote-dir: /geojson
          branch-name: assets
      
      - name: Replace GeoJSON URL in Issue Body
        if: env.HAS_ROUTE_LABEL == 'true'
        id: update-issue
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const oldBody = `${{ github.event.issue.body }}`;
            const newUrl = "https://github.com/yougikou/yougikou.github.io/blob/assets/geojson/${{ github.event.issue.number }}-route.geojson?raw=true";
            const newBody = oldBody.replace(/geojson: \'\[file\]\(.*?\)'/g, `geojson: '[file](${newUrl})'`);
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: newBody,
            });
