name: Download and Update GeoJSON

on:
  issues:
    types: [opened, labeled]

jobs:
  download-and-update-geojson:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract GeoJSON URL
        id: extract-url
        run: |
          echo "GEOJSON_URL=$(echo '${{ github.event.issue.body }}' | grep -oP 'geojson: \'\[file\]\((.*?)\)' | sed -n "s/geojson: '\[file\]\((.*?)\)/\1/p")" >> $GITHUB_ENV
        shell: bash
      
      - name: Download and Upload GeoJSON File
        uses: wow-actions/download-upload@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          url: ${{ env.GEOJSON_URL }}
          dir: assets
          filename: ${{ github.event.issue.number }}-route.geojson

      - name: Replace GeoJSON URL in Issue Body
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const oldBody = `${{ github.event.issue.body }}`;
            const newUrl = "https://github.com/yougikou/yougikou.github.io/blob/master/assets/${{ github.event.issue.number }}-route.geojson?raw=true";
            const newBody = oldBody.replace(/geojson: \'\[file\]\(.*?\)'/g, `geojson: '[file](${newUrl})'`);
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: newBody,
            });
